server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location = / {
        return 301 $scheme://$http_host/index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
